name: Deploy to FTP

# This workflow is triggered on pushes to the repository.
on: push

jobs:
  ftp-deploy:
    name: Deploy to FTP Server
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build React App
      run: |
        npm install
        npm run build

    - name: List build directory contents
      run: ls -R build

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        ftp-server: ftp://${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: build/
        git-ftp-args: --insecure
        remote-dir: ${{ secrets.FTP_REMOTE_DIR }}
